language: node_js
node_js:
  - 4.2
sudo: false
env:
  global:
    - CXX=g++-4.8
    - SAUCE_USERNAME=metaxy
    - secure: "L8/FExktFJeQoiFnMu3xtGiyDpbn6o5a8YuAM4RNdyelWKHuN6t99tobZIAPRvQMNRS9MSX+f+TypORtz1i6cEIjUxregRiGvDX9FHFIfu+uJ+7uce+2JpTCcylZO6nLv1POokDjGq6Aofgf/ti74NhTdpjbme3/7sD6vnzl5jj5PFkVPgaQqYVCKP1Cntt4oGnq1aMeZiFpuSsspQRonL8HFIJOT59C7IVOzlD6AZW0PJMHEz7cFFRWadgkluQVpyHU3fZcb5nvwozNdhGHLi3uBUNQYidAzF0rHZQvJQsSOkrPrwkEoVLgCtrQiKg68ukKU/JYd1AAQTl6ORdr1GeiJdyz1pMpHGLgCRGUgBSpn9KJRNMHo8G/3ugS+0eJwyJ8BiVh0fsaMzqu5LWR9WADkYn20LtQIPyxyM/s73dLUhRPCwFqrkLymSpyR0ze8N9dse+CeNrzsPbJRbiso0kJRRjnYdZ1I7IBzJ67ZW+4wBEVnzMpJzQCLxLL4shHPdU2kc8LQJnWfs3ogvJMftmxV6Zh9YTn+HHKzu9Fl43UUmcnaAMv/Sd48RswX4xR+OrIEfr1ZAw7lG8pgcGu0kUroBx7K4QLsJVIgv0oBeGf3IoaQ2SEmUH6VeljiYJN8O3fnSPc672UAD215COnDEbgHSnQzqE5pYJoZ6bLQos="
branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - "$HOME/.nvm"
    - node_modules
    - bower_components
before_install:
  - openssl aes-256-cbc -K $encrypted_f977bfde2ef3_key -iv $encrypted_f977bfde2ef3_iv -in id_rsa.enc -out id_rsa -d
  - npm install -g bower gulp
  - cp id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm set progress=false
install:
  - npm install
  - npm install -g strong-build
  - bower install
before_script:
  - export NODE_ENV="travis"
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start &
  - sleep 2
script:
  - gulp build
  - gulp test
  - ls dist/
after_success:
  - sh deploy.sh

