language: node_js
node_js:
  - iojs
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.nvm
before_install:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g nodemon
install:
  - npm install
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start &
  - sleep 2
script:
  - gulp protractor
