language: node_js
node_js:
- iojs-2.5.0
sudo: false
services:
- mongodb
cache:
  directories:
  - bower_components
  - "$HOME/.nvm"
before_install:
- openssl aes-256-cbc -K $encrypted_f977bfde2ef3_key -iv $encrypted_f977bfde2ef3_iv
  -in id_rsa.pub.enc -out .ssh/id_rsa.pub -d
- openssl aes-256-cbc -K $encrypted_f977bfde2ef3_key -iv $encrypted_f977bfde2ef3_iv
  -in id_rsa.enc -out .ssh/id_rsa -d
- npm install -g bower gulp
install:
- npm install
- bower install
before_script:
- export NODE_ENV="travis"
- sleep 10
- mongo mydb_test --eval 'db.addUser("travis", "test");'
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start &
- sleep 2
script:
- gulp test
- gulp build
- sh deploy.sh
