language: node_js
node_js:
  - 4.2
sudo: false
env:
  - CXX=g++-4.8
branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - bower_components
    - "$HOME/.nvm"
before_install:
  - openssl aes-256-cbc -K $encrypted_f977bfde2ef3_key -iv $encrypted_f977bfde2ef3_iv -in id_rsa.enc -out id_rsa -d
  - npm install -g bower gulp
  - cp id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - npm install
  - bower install
before_script:
  - export NODE_ENV="travis"
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start &
  - sleep 2
script:
  - gulp build
after_success:
  - sh deploy.sh

