language: node_js
node_js:
  - iojs-2.5.0
sudo: false
cache:
  directories:
    - bower_components
    - $HOME/.nvm
before_install:
  - npm install -g bower gulp 
install:
  - npm install
  - bower install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start &
  - sleep 2
script:
  - gulp test
